import Head from 'next/head'
import Header from '../../components/header/Header'
import React, { useState } from 'react';

function AdmingLogin({data,baseUrl}) {

    const [response, setResponse] = React.useState('');
    const [email, setEmail] = React.useState('');
    const [password, setpassword] = useState(''); // console.log(res)
    async function submitForm(e){
        e.preventDefault();
        try{
            const response= await fetch('http://localhost:3001'+'/admin/login',{
                method:'POST',
                headers:{
                    'Content-type':'application/json'
                },
                body:JSON.stringify({email,password})
            })
            const responseData= await response.json()
            console.log("res:=> ")
            console.log(responseData.token)
        }catch(e){

        }
        
    }
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header baseUrl={baseUrl}/>
      <div className='container mx-auto'>
        <form method='POST' action={'http://localhost:3001'+'/admin/login'}>
            <input className='border' name='username' type='text' value={email} onChange={(e)=>setEmail(e.target.value)}/>
            <input className='border' name='pass' type='text' value={password} onChange={(e)=>setpassword(e.target.value)}/>
            <input className='border'  type='submit' onClick={(e)=>submitForm(e)} />
            {/* */}
        </form>
      </div>
    </>
      
  )
}

export async function getStaticProps() {
  // console.log(process.env.API_URL)
  // Call an external API endpoint to get posts
  const res = await fetch(process.env.API_URL)
  const data = await res.json()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      data,
      baseUrl:process.env.API_URL
    },
  }
}

export default AdmingLogin