import Head from "next/head";
import Hero from "../components/Hero/Hero";
import Header from "../components/Header/Header";
import Projects from '../components/Projects/Projects'
import { useSession } from "next-auth/react";
import { signOut } from "next-auth/react"
import { useRouter } from "next/router";
import axios from "axios";

function Home( {data} ) {
  const { data: session } = useSession();
  const router = useRouter();
  console.log("session: ", session);
  return (
    <>
      <Head>
        <title>Seyed Ali Dehghan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <Hero description={data.setting.description} socials={data.social}/>
      <Projects projects={data.projects}/>
    </>
  );
}

export async function getStaticProps() {
  const res = await axios.get(process.env.URL+"/api")
  // console.log(res)
  // const res = await fetch("http://localhost:3000/api")
  // const data = await res.json()
  return {
    props: {
      data:res.data
    },
  }
}

export default Home;



// {session ? (
//   <button onClick={() => signOut()}>logout</button>
// ) : (
//   <button
//     onClick={() => {
//       router.push("/api/auth/signin");
//     }}
//   >
//     login
//   </button>
// )}