import Head from 'next/head'
import Hero from '../components/Hero/Hero'
import Header from '../components/header/Header'
export default function Home() {
  return (
    <>
      <Head>
        <title>سید علی دهقان</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      {/* hero section */}
      <Hero/>
    </>
      
  )
}