import Head from 'next/head'
import Hero from '../components/Hero/Hero'
import Header from '../components/header/Header'
function Home({data,baseUrl}) {
  return (
    <>
      <Head>
        <title>سید علی دهقان</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header baseUrl={baseUrl}/>
      {/* hero section */}
      <Hero/>
    </>
      
  )
}

export async function getStaticProps() {
  // console.log(process.env.API_URL)
  // Call an external API endpoint to get posts
  const res = await fetch(process.env.API_URL)
  const data = await res.json()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      data,
      baseUrl:process.env.API_URL
    },
  }
}

export default Home